GapIntelligence/gapintelligence-gem

- lib/gap_intelligence/client/brands.rb
- lib/gap_intelligence/client/categories.rb
- lib/gap_intelligence/client/downloads.rb
- lib/gap_intelligence/client/merchants.rb
- lib/gap_intelligence/client/requestable.rb
This pull request adds ability to pass custom `record_class` to request methods.
> Make record class to be acceptable

- lib/gap_intelligence/models/download.rb
- lib/gap_intelligence/models/record.rb
The same for gAPI https://github.com/GapIntelligence/gapi/pull/976
> Add missing attributes to download

- lib/gap_intelligence/client/headers.rb
- spec/factories/headers.rb
- spec/gap/client/headers_spec.rb
https://www.pivotaltracker.com/story/show/117833171
> Get pricing headers through gem

- lib/gap_intelligence/models/category.rb
- spec/factories/categories.rb
- spec/gap/models/category_spec.rb
- spec/support/record_shared.rb
related to https://www.pivotaltracker.com/story/show/118398665
> Add full_name attribute to category

- lib/gap_intelligence/client/merchant_pricing_trend_downloads.rb
- spec/gap/client/merchant_pricing_trend_downloads_spec.rb
https://www.pivotaltracker.com/story/show/121962783
> Add index action for MPT downloads

- lib/gap_intelligence/client/downloads.rb
- lib/gap_intelligence/client/requestable.rb
- lib/gap_intelligence/models/download.rb
- spec/factories/downloads.rb
- spec/gap/client/downloads_spec.rb
- spec/gap/models/download_spec.rb
This pull request adds ability to retrieve data for specific download.
https://www.pivotaltracker.com/story/show/122045997
> Add ability to get specific download by id

- lib/gap_intelligence/client.rb
- lib/gap_intelligence/configuration.rb
This pull request adds ability to configure faraday when creating client.
> Extend client configuration

- lib/gap_intelligence/client/downloads.rb
- lib/gap_intelligence/client/merchant_pricing_trend_downloads.rb
- spec/gap/client/merchant_pricing_trend_downloads_spec.rb
This pull request updates MPTD delete method to provide ability to delete multiple downloads.
> Update MPTD delete method

- lib/gap_intelligence/models/category.rb
- spec/factories/categories.rb
- spec/gap/models/category_spec.rb
depends on https://github.com/GapIntelligence/gapi/pull/1198
> Add frequency to category

- lib/gap_intelligence/models/category.rb
- spec/factories/categories.rb
- spec/gap/models/category_spec.rb
Feature/category published date 138676675
> Add published date to categories

- lib/gap_intelligence/client.rb
- lib/gap_intelligence/client/brands.rb
- lib/gap_intelligence/client/categories.rb
- lib/gap_intelligence/client/downloads.rb
- lib/gap_intelligence/client/files.rb
- lib/gap_intelligence/client/headers.rb
- lib/gap_intelligence/client/merchant_pricing_trend_downloads.rb
- lib/gap_intelligence/client/merchant_pricing_trends.rb
- lib/gap_intelligence/client/merchants.rb
- lib/gap_intelligence/configuration.rb
- spec/gap/client_spec.rb
- spec/support/stubs.rb
This pull request adds HTTPS support.
> Add HTTPS support

- lib/gap_intelligence/client/merchant_pricing_trend_downloads.rb
- spec/gap/client/merchant_pricing_trend_downloads_spec.rb
This pull request adds ability to get merchant pricing trend download by id.
> Add ability to get merchant pricing trend download by id

- lib/gap_intelligence/client/products.rb
- spec/gap/client/products_spec.rb
https://www.pivotaltracker.com/story/show/149599403
> Add ability to query single product

- lib/gap_intelligence/client.rb
- lib/gap_intelligence/client/product_presence.rb
- spec/gap/client/product_presence_spec.rb
https://www.pivotaltracker.com/story/show/149257455
> add product presence endpoint with specs

- lib/gap_intelligence.rb
- lib/gap_intelligence/client.rb
- lib/gap_intelligence/client/ad_shares.rb
- lib/gap_intelligence/models/ad_share.rb
- spec/factories/ad_shares.rb
- spec/gap/client/ad_shares_spec.rb
- spec/gap/models/ad_share_spec.rb
https://www.pivotaltracker.com/story/show/149257455
> Add ad shares end point with specs

- lib/gap_intelligence/client.rb
- lib/gap_intelligence/client/product_snapshot.rb
- spec/factories/ad_shares.rb
- spec/factories/product_snapshots.rb
- spec/gap/client/product_snapshot_spec.rb
This pull request adds product snapshot endpoint.
> Add product snapshot endpoint

- lib/gap_intelligence/models/category.rb
- spec/gap/models/category_spec.rb
https://www.pivotaltracker.com/story/show/152939864
> add publish_tag_only attribute to category model

- lib/gap_intelligence/client/brands.rb
- spec/gap/client/brands_spec.rb
https://www.pivotaltracker.com/story/show/153600887
> update brands enpoint params

- lib/gap_intelligence/models/category.rb
- spec/gap/models/category_spec.rb
this PR adds product location to category
> add product location attribute to category

- lib/gap_intelligence/models/advertisement.rb
https://www.pivotaltracker.com/story/show/164215501
> Add ad type to Ad model

- lib/gap_intelligence/client.rb
- lib/gap_intelligence/client/ad_pages.rb
- lib/gap_intelligence/models/ad_image.rb
- spec/factories/ad_images.rb
- spec/factories/ad_pages.rb
- spec/gap/client/ad_pages_spec.rb
This pull request adds Ad Page endpoint support.
https://www.pivotaltracker.com/story/show/166744377
> Add Ad Page endpoint support

- lib/gap_intelligence/client/ad_images.rb
https://github.com/GapIntelligence/pretty-bird/pull/596
> Add show endpoint method for ad images

- lib/gap_intelligence/client.rb
- lib/gap_intelligence/configuration.rb
https://www.pivotaltracker.com/story/show/167468600
> add ability to pass connection_opts

- lib/gap_intelligence/models/category_version.rb
- spec/gap/models/category_version_spec.rb
Adds display cents method to category version model so it can be accessed by the Neo Card
https://www.pivotaltracker.com/story/show/175418027
> Adds display cents to Category Version Model

- lib/gap_intelligence/client/promo_matrix.rb
- spec/gap/client/promo_matrix_spec.rb
Changes Promo Matrix requests to allow post requests
https://www.pivotaltracker.com/story/show/175550135
> Change Promo Matrix Requests to Allow Post Requests

- lib/gap_intelligence/models/product.rb
- spec/gap/models/product_spec.rb
This pull request adds product_version_id attribute to Product model.
https://www.pivotaltracker.com/story/show/174535938
> Add product_version_id attribute to Product model

- lib/gap_intelligence/models/category_version.rb
- spec/gap/models/category_version_spec.rb
https://www.pivotaltracker.com/story/show/176721287
> Add icon to category version

- gap_intelligence.gemspec
https://www.pivotaltracker.com/n/projects/1941863/stories/173068928
> Rake upgraded to version 12.3.3

- gap_intelligence.gemspec
this PR updates bundler version
https://www.pivotaltracker.com/story/show/178287704
> update bundler to 2.2.10

- lib/gap_intelligence/client/headers.rb
- lib/gap_intelligence/models/download.rb
- spec/factories/headers.rb
- spec/gap/client/headers_spec.rb
https://www.pivotaltracker.com/story/show/179743486
> Add Copier Headers

- lib/gap_intelligence/client/brands.rb
- lib/gap_intelligence/models/download.rb
- spec/factories/downloads.rb
- spec/gap/client/brands_spec.rb
**Story:**
- https://www.pivotaltracker.com/story/show/178095961
This PR adds new request method - printer_brands
> Feature - Brands: printer_brands request

- lib/gap_intelligence/models/merchant_pricing_trend_download.rb
- spec/factories/merchant_pricing_trend_downloads.rb
- spec/gap/models/merchant_pricing_trend_download_spec.rb
https://www.pivotaltracker.com/story/show/181038298
> Add Category Versions to Merchant Pricing Trends download

- lib/gap_intelligence/client/merchant_pricing_trends.rb
- lib/gap_intelligence/models/brand.rb
- lib/gap_intelligence/models/calculated_pricing.rb
- spec/factories/brands.rb
- spec/gap/client/merchant_pricing_trends_spec.rb
- spec/gap/models/calculated_pricing_spec.rb
https://www.pivotaltracker.com/story/show/180966969
> Update MPT pricings endpoint to send POST and serializers

- lib/gap_intelligence/client.rb
- lib/gap_intelligence/models/category_version.rb
- spec/gap/models/category_version_spec.rb
This pull request updates category version to support currency.
- Updated client to improve error messaging
https://www.pivotaltracker.com/story/show/181585986
> Update category version to support currency

- lib/gap_intelligence/models/calculated_pricing.rb
- spec/factories/calculated_pricings.rb
- spec/gap/models/calculated_pricing_spec.rb
**Story:**
- https://www.pivotaltracker.com/story/show/182263696
This PR adds :in_stock, :previous_shelf_price, :previous_net_price attributes into Calculated Pricings
> Feature: Calculated Pricing previous price and stock status attributes

- lib/gap_intelligence/client.rb
- lib/gap_intelligence/client/delta.rb
- spec/factories/delta.rb
- spec/gap/client/delta_spec.rb
This pull request adds Delta Aggregate endpoint.
https://www.pivotaltracker.com/story/show/182931474
> Add Delta Aggregate endpoint

- lib/gap_intelligence/client.rb
- lib/gap_intelligence/client/pricing_images.rb
- lib/gap_intelligence/models/in_store_image.rb
- lib/gap_intelligence/models/pricing_image.rb
- spec/factories/pricing_images.rb
- spec/gap/client/pricing_images_spec.rb
https://www.pivotaltracker.com/story/show/184597237
> Add pricing images show endpoint

- lib/gap_intelligence/models/in_store_image.rb
- lib/gap_intelligence/models/pricing_image.rb
- spec/gap/models/in_store_image_spec.rb
**Story:**
- https://www.pivotaltracker.com/story/show/185561969
> Bug: In Store Image - Update Serializer
